Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\maha0\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\maha0\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maha0\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maha0\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maha0\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\maha0\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
## Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
#create a series from dictionary

data ={'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
index = ['a', 'b', 'c']
pd.Series(data, index)

a    10
b    20
c    30
dtype: int64

In [6]:
##Dataframe 
#create  a data from a dictionary of list

data ={
    'name': ['krish', 'jon', 'jack'],
    'age': [25, 30, 45],
    'city': ['bangalore', 'new york', 'Mumbai']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai
<class 'pandas.core.frame.DataFrame'>

In [7]:
#create a dataframe from a list of dictionaries

data = [
    {'name': "Mohsin", 'age': 32, 'ciy': 'Mumbai'},
    {'name': "Maha", 'age': 31, 'ciy': 'Mumbai'},
    {'name': "Abbas", 'age': 30, 'ciy': 'Mumbai'},
    {'name': "dan", 'age': 34, 'ciy': 'Mumbai'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age     ciy
0  Mohsin   32  Mumbai
1    Maha   31  Mumbai
2   Abbas   30  Mumbai
3     dan   34  Mumbai
<class 'pandas.core.frame.DataFrame'>

In [23]:

df = pd.read_csv('sales_data.csv')
#print(df.head(5))
#print(df.tail(5))
#print(df)
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [4]:
#Accessing data from Dataframe
data ={
    'name': ['krish', 'jon', 'jack'],
    'age': [25, 30, 45],
    'city': ['bangalore', 'new york', 'Mumbai']
}

df = pd.DataFrame(data)
print(df)

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai

In [26]:
print(type(df['name']))
print(df['name'])

<class 'pandas.core.series.Series'>
0    krish
1      jon
2     jack
Name: name, dtype: object

In [27]:
df.loc[0]

name        krish
age            25
city    bangalore
Name: 0, dtype: object

In [13]:
df.iloc[1][2]

C:\Users\maha0\AppData\Local\Temp\ipykernel_16672\65333983.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][2]

'new york'

In [14]:
df

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai

In [32]:
#Accessing a special element
df['name']
df.at[1,'age']
df.at[2,'city']

'Mumbai'

In [35]:
##Accesssing a specified element using iat
#The primary difference between .at and .iat in pandas is how they access data: .at uses row/column labels, while .iat uses integer positions (0-based indexing).
df.iat[2,1]

45

In [36]:
df

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai

In [5]:
#data Manupulaion with dataframe
print(df)

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai

In [6]:
#adding a column
df['salary']= [50000, 60000, 70000]
print(df)

    name  age       city  salary
0  krish   25  bangalore   50000
1    jon   30   new york   60000
2   jack   45     Mumbai   70000

In [7]:
#remove a column 
df.drop('salary', axis=1,inplace=True)
print(df)

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai

In [74]:
print(df)

    name  age       city
0  krish   25  bangalore
1    jon   30   new york
2   jack   45     Mumbai

In [8]:
#adding to age of the column
df['age'] = df['age']+1
print(df)

    name  age       city
0  krish   26  bangalore
1    jon   31   new york
2   jack   46     Mumbai

In [14]:
df.drop(1, inplace=True)

In [15]:
df

    name  age       city
0  krish   26  bangalore
2   jack   46     Mumbai

In [18]:
df = pd.read_csv('sales_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [20]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [22]:
#display the data type of each column
print("data types: \n", df.dtypes)

data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [23]:
#describe the dataframe
print("statical summary\n", df.describe())

statical summary
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000